site_name: Arno Store
nav:
  - Header:
    - Meta Tags: custom-features/header/meta-tags.md
    - Data Structure: custom-features/header/data-structure.md
    - Black Bar: custom-features/header/top-black-bar.md
    - Menu Bar: custom-features/header/new-menu-bar.md
    - Black Button: custom-features/header/black-button.md
  - Account:
    - Script Yami: custom-features/account/script-yami.md
  - Home:
    - Custom Croct Popup: custom-features/home/custom-croct-popup.md
    - Newsletter Popup: custom-features/home/newsletter-popup.md
    - Slider Hero: custom-features/home/slider-hero.md
    - Main Categories: custom-features/home/main-categories.md
    - Home Tabs: custom-features/home/home-tabs.md
    - Shelf Lancamentos: custom-features/home/shelf-lancamentos.md
    - Special Selection: custom-features/home/special-selection.md
  - PDP:
    - Send Event: custom-features/pdp/send-event-pdp.md
    - Comparator: custom-features/pdp/comparator.md
    - Blog Post: custom-features/pdp/blog-pdp.md
    - Enriched Content: custom-features/pdp/enriched-content.md
    - Redirect to Reviews: custom-features/pdp/redirect-reviews.md
  - Search:
    - Meta Tags Categories: custom-features/search/meta-tags-categories.md
  - Minicart:
    - Gift Bar: custom-features/minicart/arno-minicart-giftbar.md
    - Coupon Form: custom-features/minicart/coupon-form-minicart.md
    - Price Resume: custom-features/minicart/custom-arno-resume-price-minicart.md
    - Custom Price: custom-features/minicart/change-price-minicart.md
    - Cross Selling: custom-features/minicart/cross-selling.md
  - Blog:
    - Blog API Masterdata: custom-features/blog/api-masterdata.md
    - Blog Home: custom-features/blog/home.md
    - Blog Categories: custom-features/blog/categories.md
    - Blog Category: custom-features/blog/category.md
    - Blog Post: custom-features/blog/post.md
    - Blog Tag: custom-features/blog/tag.md
  - Institutional:
    - Vendas Corporativas: custom-features/institutional/venda-corporativa-form.md
    - Black Friday 2025: custom-features/institutional/black-friday-2025.md
  - Shelves:
    - Ofertas Relâmpago: custom-features/shelves/ofertas-relampago.md
  - Checkout:
    - Awin Cookies: custom-features/checkout/awin-cookies.md
    - Awin Conversion: custom-features/checkout/awin-conversion.md
    - Checkout UI Custom: custom-features/checkout/checkout-ui-custom.md
  - Global:
    - Pixel APP: custom-features/global/pixel-app.md
  - Site Editor:
    - Top Black Bar: site-editor/header/top-black-bar.md
    - Black Button: site-editor/header/black-button.md
    - Menu Desktop: site-editor/header/menu-desktop.md
    - Menu Mobile: site-editor/header/menu-mobile.md
    - Search Header:  site-editor/search/banner.md
    - Coleção de produtos: site-editor/search/collection.md
    - Slider Hero: site-editor/home/slider-hero.md
    - Ofertas Relâmpago: site-editor/home/ofertas-relampago.md
    - Seleção Especial: site-editor/home/selecao-especial.md
    - Main Categories: site-editor/home/main-categories.md
    - Barra de Benefícios: site-editor/home/barra-de-beneficios.md
    - Shelf Lancamentos: site-editor/home/shelf-lancamentos.md
    - Vitrine multibranding: site-editor/home/vitrine-multibranding.md
    - Marcas Home: site-editor/home/marcas-home.md
    - Newsletter Home: site-editor/home/newsletter.md
    - SEO: site-editor/search/seo-pdc.md
  - VTEX:
    - Nova Página Coleção: vtex/new-collection-page.md
    - Como alimentar o Blog Arno: vtex/blog-masterdata.md
theme:
  name: material
  font:
    text: Inter
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/Groupe-SEB-BR/Arno-Store
repo_name: Arno-Store


