site_name: Arno Store
nav:
  - Header:
    - Black Bar: custom-features/header/top-black-bar.md
    - Menu Bar: custom-features/header/new-menu-bar.md
    - Black Button: custom-features/header/black-button.md
  - Home:
    - Popup: custom-features/home/home-popup.md
    - Slider Hero: custom-features/home/slider-hero.md
    - Main Categories: custom-features/home/main-categories.md
    - Home Tabs: custom-features/home/home-tabs.md
    - Shelf Lancamentos: custom-features/home/shelf-lancamentos.md
    - Special Selection: custom-features/home/special-selection.md
  - PDP:
    - Blog Post: custom-features/pdp/blog-pdp.md
    - Enriched Content: custom-features/pdp/enriched-content.md
  - Minicart:
    - Gift Bar: custom-features/minicart/arno-minicart-giftbar.md
    - Coupon Form: custom-features/minicart/coupon-form-minicart.md
    - Price Resume: custom-features/minicart/custom-arno-resume-price-minicart.md
    - Custom Price: custom-features/minicart/custom-price-minicart.md
    - Cross Selling: custom-features/minicart/cross-selling.md
    - Custom Arno Discount Popup: custom-features/minicart/custom-arno-discount-popup.md
  - Blog:
    - Blog API Masterdata: custom-features/blog/api-masterdata.md
    - Blog Home: custom-features/blog/home.md
    - Blog Categories: custom-features/blog/categories.md
    - Blog Category: custom-features/blog/category.md
    - Blog Post: custom-features/blog/post.md
    - Blog Tag: custom-features/blog/tag.md
  - Global Features:
    - Meta Tags: custom-features/home/meta-tags.md
    - Data Structure: custom-features/home/data-structure.md
    - Flash Sales: custom-features/home/flash-sales-home.md
    - Flash Sales: custom-features/shelves/ofertas-relampago.md
  - Legado:
    - Custom Croct Popup: custom-features/minicart/custom-croct-popup.md
    - Croct Controler Component: custom-features/minicart/croct-controler-component.md
theme:
  name: material
  font:
    text: Inter
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/Groupe-SEB-BR/Arno-Store
repo_name: Arno-Store


